source 'https://rubygems.org'

ruby '~> 3.0'

# Web framework
gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'puma', '~> 6.4'
gem 'rackup', '~> 2.1'

# Database
gem 'pg', '~> 1.5'
gem 'sequel', '~> 5.75'

# CORS support
gem 'rack-cors', '~> 2.0'

# JSON handling
gem 'oj', '~> 3.16'

# Environment variables
gem 'dotenv', '~> 3.0'

# Validation
gem 'dry-validation', '~> 1.10'
gem 'dry-monads', '~> 1.6'

group :development do
  gem 'rerun', '~> 0.14'
end

group :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'simplecov', '~> 0.22', require: false
  gem 'webmock', '~> 3.19'
  gem 'database_cleaner-sequel', '~> 2.0'
end
